In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
all_set = pd.read_csv('./data/[회귀]all_2차_전처리_완료.csv')

In [5]:
df17 = all_set[all_set['연도'] == 2017]
df18 = all_set[all_set['연도'] == 2018]
df19 = all_set[all_set['연도'] == 2019]

In [10]:
all_set['입출구명'].unique()

array(['구의문', '후문', '정문', '사전무인', '서버실'], dtype=object)

# 2017년 입장문별 데이터 분리

In [11]:
df17_guiient = df17[df17['입출구명'] == '구의문']
df17_backent = df17[df17['입출구명'] == '후문']
df17_frontent = df17[df17['입출구명'] == '정문']

In [14]:
df17_guiient

,진입시각,진출시각,입출구명,고객구분,차종,주차시간(분),연도,in_year,in_month,in_date,in_hour,in_minute,in_second,out_year,out_month,out_date,out_hour,out_minute,out_second
0,2017-01-01 09:02:31,2017-01-01 09:40:45,구의문,일반,소형,39,2017,2017,1,1,9,2,31,2017,1,1,9,40,45
2,2017-01-01 09:04:09,2017-01-01 11:56:39,구의문,정기권,소형,173,2017,2017,1,1,9,4,9,2017,1,1,11,56,39
4,2017-01-01 09:05:27,2017-01-01 10:04:45,구의문,일반,소형,60,2017,2017,1,1,9,5,27,2017,1,1,10,4,45
5,2017-01-01 09:05:32,2017-01-01 10:03:53,구의문,일반,소형,59,2017,2017,1,1,9,5,32,2017,1,1,10,3,53
21,2017-01-01 10:03:25,2017-01-01 14:34:13,구의문,일반,소형,271,2017,2017,1,1,10,3,25,2017,1,1,14,34,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489535,2017-12-31 20:56:30,2017-12-31 21:34:54,구의문,일반,소형,39,2017,2017,12,31,20,56,30,2017,12,31,21,34,54
489589,2017-12-31 19:26:27,2017-12-31 21:49:37,구의문,일반,소형,143,2017,2017,12,31,19,26,27,2017,12,31,21,49,37
489591,2017-12-31 17:46:43,2017-12-31 21:50:03,구의문,일반,경차,244,2017,2017,12,31,17,46,43,2017,12,31,21,50,3
489594,2017-12-31 16:15:18,2017-12-31 21:51:03,구의문,일반,소형,336,2017,2017,12,31,16,15,18,2017,12,31,21,51,3
489620,2017-12-31 14:48:05,2017-12-31 22:27:03,구의문,일반,소형,459,2017,2017,12,31,14,48,5,2017,12,31,22,27,3

# 카운팅 데이터프레임 만들기

In [15]:
counting_df_2017 = pd.DataFrame()
counting_df_2017['datetime'] = pd.date_range("2017-01-01", "2018-01-01", freq='H')
counting_df_2017.dtypes

datetime    datetime64[ns]
dtype: object

## [구의문] 시각 기준으로 count

In [43]:
def counting_hourly(counting_df, row, counter):
    compare_month = counting_df['datetime'].dt.month == row['in_month']
    compare_date = counting_df['datetime'].dt.day == row['in_date']
    compare_in_hour = counting_df['datetime'].dt.hour >= row['in_hour']
    compare_out_hour = counting_df['datetime'].dt.hour <= row['out_hour']
    
    counter.append(list(counting_df.loc[compare_month & compare_date & compare_in_hour & compare_out_hour]['datetime']))
    pass

In [44]:
counter_guii_2017 = []
df17_guiient.apply(lambda row: counting_hourly(counting_df_2017, row, counter_guii_2017), axis=1)
counter_guii_2017[:30]

[[Timestamp('2017-01-01 09:00:00')],
 [Timestamp('2017-01-01 09:00:00'),
  Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00')],
 [Timestamp('2017-01-01 09:00:00'), Timestamp('2017-01-01 10:00:00')],
 [Timestamp('2017-01-01 09:00:00'), Timestamp('2017-01-01 10:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00'),
  Timestamp('2017-01-01 14:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00'),
  Timestamp('2017-01-01 14:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'), Timestamp('2017-01-01 11:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00'),
  Timestamp('2017-01-01 14:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00'),
  Timestamp('2017-01-01 14:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'), Timestamp('2017-01-01 11:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 10:00:00'),
  Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 11:00:00'), Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 11:00:00'), Timestamp('2017-01-01 12:00:00')],
 [Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00')],
 [Timestamp('2017-01-01 11:00:00'),
  Timestamp('2017-01-01 12:00:00'),
  Timestamp('2017-01-01 13:00:00'),
  Timestamp('2017-01-01 14:00:00'),
  Timestamp('2017-01-01 15:00:00')]]

In [45]:
counter_guii_2017_save = counter_guii_2017.copy()

In [46]:
counter_guii_2017 = [item for item_list in counter_guii_2017 for item in item_list]
counter_guii_2017

[Timestamp('2017-01-01 09:00:00'),
 Timestamp('2017-01-01 09:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 09:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 09:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 10:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 11:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 12:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 19:00:00'),
 Timestamp('2017-01-01 20:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 13:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 14:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 19:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 19:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 15:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 16:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 17:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 18:00:00'),
 Timestamp('2017-01-01 20:00:00'),
 Timestamp('2017-01-01 21:00:00'),
 Timestamp('2017-01-01 21:00:00'),
 Timestamp('2017-01-01 22:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 19:00:00'),
 Timestamp('2017-01-02 20:00:00'),
 Timestamp('2017-01-02 21:00:00'),
 Timestamp('2017-01-02 22:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 09:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 19:00:00'),
 Timestamp('2017-01-02 20:00:00'),
 Timestamp('2017-01-02 21:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 10:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 13:00:00'),
 Timestamp('2017-01-02 14:00:00'),
 Timestamp('2017-01-02 15:00:00'),
 Timestamp('2017-01-02 16:00:00'),
 Timestamp('2017-01-02 17:00:00'),
 Timestamp('2017-01-02 18:00:00'),
 Timestamp('2017-01-02 11:00:00'),
 Timestamp('2017-01-02 12:00:00'),
 Timestamp('2017-01-02 11:00:00'),

In [47]:
counter_guii_2017 = pd.DataFrame(counter_guii_2017).rename(columns={0 : 'datetime'})
counter_guii_2017['count'] = 1

In [48]:
counter_guii_2017.head()

             datetime  count
0 2017-01-01 09:00:00      1
1 2017-01-01 09:00:00      1
2 2017-01-01 10:00:00      1
3 2017-01-01 11:00:00      1
4 2017-01-01 09:00:00      1

In [49]:
counter_guii_2017 = counter_guii_2017.groupby('datetime').count().reset_index()
counter_guii_2017[:30]

              datetime  count
0  2017-01-01 09:00:00      4
1  2017-01-01 10:00:00     23
2  2017-01-01 11:00:00     39
3  2017-01-01 12:00:00     44
4  2017-01-01 13:00:00     50
5  2017-01-01 14:00:00     59
6  2017-01-01 15:00:00     65
7  2017-01-01 16:00:00     53
8  2017-01-01 17:00:00     31
9  2017-01-01 18:00:00     13
10 2017-01-01 19:00:00      3
11 2017-01-01 20:00:00      2
12 2017-01-01 21:00:00      2
13 2017-01-01 22:00:00      1
14 2017-01-02 09:00:00      9
15 2017-01-02 10:00:00     21
16 2017-01-02 11:00:00     39
17 2017-01-02 12:00:00     51
18 2017-01-02 13:00:00     45
19 2017-01-02 14:00:00     51
20 2017-01-02 15:00:00     58
21 2017-01-02 16:00:00     47
22 2017-01-02 17:00:00     43
23 2017-01-02 18:00:00     48
24 2017-01-02 19:00:00     35
25 2017-01-02 20:00:00     23
26 2017-01-02 21:00:00     15
27 2017-01-02 22:00:00      2
28 2017-01-03 09:00:00     21
29 2017-01-03 10:00:00     34

In [50]:
counting_df_2017_save = pd.merge(counting_df_2017, counter_guii_2017, how='outer', on='datetime').fillna(0)
counting_df_2017_save[:30]

              datetime  count
0  2017-01-01 00:00:00    0.0
1  2017-01-01 01:00:00    0.0
2  2017-01-01 02:00:00    0.0
3  2017-01-01 03:00:00    0.0
4  2017-01-01 04:00:00    0.0
5  2017-01-01 05:00:00    0.0
6  2017-01-01 06:00:00    0.0
7  2017-01-01 07:00:00    0.0
8  2017-01-01 08:00:00    0.0
9  2017-01-01 09:00:00    4.0
10 2017-01-01 10:00:00   23.0
11 2017-01-01 11:00:00   39.0
12 2017-01-01 12:00:00   44.0
13 2017-01-01 13:00:00   50.0
14 2017-01-01 14:00:00   59.0
15 2017-01-01 15:00:00   65.0
16 2017-01-01 16:00:00   53.0
17 2017-01-01 17:00:00   31.0
18 2017-01-01 18:00:00   13.0
19 2017-01-01 19:00:00    3.0
20 2017-01-01 20:00:00    2.0
21 2017-01-01 21:00:00    2.0
22 2017-01-01 22:00:00    1.0
23 2017-01-01 23:00:00    0.0
24 2017-01-02 00:00:00    0.0
25 2017-01-02 01:00:00    0.0
26 2017-01-02 02:00:00    0.0
27 2017-01-02 03:00:00    0.0
28 2017-01-02 04:00:00    0.0
29 2017-01-02 05:00:00    0.0

In [51]:
counting_df_2017_save.to_csv('./data/[회귀]실이용객_시각별_차량_카운트_구의문_2017.csv', index=False)

# [입장문별] 시각 기준 카운팅

In [54]:
def iter_counter(counting_df, df_ent):
    counter = []
    df_ent.apply(lambda row: counting_hourly(counting_df, row, counter), axis=1)
    counter_save = counter.copy()
    counter = [item for item_list in counter for item in item_list]
    counter = pd.DataFrame(counter).rename(columns={0 : 'datetime'})
    counter['count'] = 1
    counter = counter.groupby('datetime').count().reset_index()
    counter_2018_save = pd.merge(counting_df, counter, how='outer', on='datetime').fillna(0)
    return counter_2018_save

In [55]:
# 정문
iter_counter(counting_df_2017, df17_frontent).to_csv('./data/[회귀]실이용객_시각별_차량_카운트_정문_2017.csv', index=False)

In [56]:
# 후문
iter_counter(counting_df_2017, df17_backent).to_csv('./data/[회귀]실이용객_시각별_차량_카운트_후문_2017.csv', index=False)