In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

%matplotlib inline

In [11]:
wc_17 = pd.read_csv('./data/[회귀]요일_날씨_입출구_2017.csv')
wc_18 = pd.read_csv('./data/[회귀]요일_날씨_입출구_2018.csv')
wc_19 = pd.read_csv('./data/[회귀]요일_날씨_입출구_2019.csv')

holi = pd.read_csv('./data/[회귀]all_공휴일.csv')

In [9]:
wc_17['datetime'] = pd.to_datetime(wc_17['datetime'])
wc_18['datetime'] = pd.to_datetime(wc_18['datetime'])
wc_19['datetime'] = pd.to_datetime(wc_19['datetime'])

# 공휴일 날짜데이터 형식으로 변환

In [24]:
holi['locdate'] = holi['locdate'].map(lambda d: str(d))

In [32]:
holi['locdate'] = pd.to_datetime(holi['locdate'].map(lambda d: f'{d[:4]}-{d[4:6]}-{d[6:]}'))

In [39]:
holi['is_holiday'] = 1

holi['year'] = holi['locdate'].dt.year
holi['month'] = holi['locdate'].dt.month
holi['date'] = holi['locdate'].dt.day

In [40]:
holi

    dateName    locdate  year  month  date  holiday
0         신정 2017-01-01  2017      1     1        1
1         설날 2017-01-27  2017      1    27        1
2         설날 2017-01-28  2017      1    28        1
3         설날 2017-01-29  2017      1    29        1
4      대체공휴일 2017-01-30  2017      1    30        1
5        삼일절 2017-03-01  2017      3     1        1
6      석가탄신일 2017-05-03  2017      5     3        1
7       어린이날 2017-05-05  2017      5     5        1
8     대통령선거일 2017-05-09  2017      5     9        1
9        현충일 2017-06-06  2017      6     6        1
10       광복절 2017-08-15  2017      8    15        1
11     임시공휴일 2017-10-02  2017     10     2        1
12       개천절 2017-10-03  2017     10     3        1
13        추석 2017-10-03  2017     10     3        1
14        추석 2017-10-04  2017     10     4        1
15        추석 2017-10-05  2017     10     5        1
16     대체공휴일 2017-10-06  2017     10     6        1
17       한글날 2017-10-09  2017     10     9        1
18     기독탄신일 2017-12-25  2017     12    25        1
19      1월1일 2018-01-01  2018      1     1        1
20        설날 2018-02-15  2018      2    15        1
21        설날 2018-02-16  2018      2    16        1
22        설날 2018-02-17  2018      2    17        1
23       삼일절 2018-03-01  2018      3     1        1
24      어린이날 2018-05-05  2018      5     5        1
25     대체휴무일 2018-05-07  2018      5     7        1
26    부처님오신날 2018-05-22  2018      5    22        1
27       현충일 2018-06-06  2018      6     6        1
28  전국동시지방선거 2018-06-13  2018      6    13        1
29       광복절 2018-08-15  2018      8    15        1
30        추석 2018-09-23  2018      9    23        1
31        추석 2018-09-24  2018      9    24        1
32        추석 2018-09-25  2018      9    25        1
33     대체휴무일 2018-09-26  2018      9    26        1
34       개천절 2018-10-03  2018     10     3        1
35       한글날 2018-10-09  2018     10     9        1
36     기독탄신일 2018-12-25  2018     12    25        1
37      1월1일 2019-01-01  2019      1     1        1
38        설날 2019-02-04  2019      2     4        1
39        설날 2019-02-05  2019      2     5        1
40        설날 2019-02-06  2019      2     6        1
41       삼일절 2019-03-01  2019      3     1        1
42      어린이날 2019-05-05  2019      5     5        1
43     대체공휴일 2019-05-06  2019      5     6        1
44    부처님오신날 2019-05-12  2019      5    12        1
45       현충일 2019-06-06  2019      6     6        1
46       광복절 2019-08-15  2019      8    15        1
47        추석 2019-09-12  2019      9    12        1
48        추석 2019-09-13  2019      9    13        1
49        추석 2019-09-14  2019      9    14        1
50       개천절 2019-10-03  2019     10     3        1
51       한글날 2019-10-09  2019     10     9        1
52     기독탄신일 2019-12-25  2019     12    25        1

In [44]:
wch_17 = wc_17.merge(holi, how='left').fillna(0)

In [43]:
wch_18 = wc_18.merge(holi, how='left').fillna(0)

In [47]:
wch_19 = wc_19.merge(holi, how='left').fillna(0)
wch_19

,datetime,count,입출구명,year,month,date,hour,weekday,기온(°C),강수량(mm),풍속(m/s),습도(%),일조(hr),일사(MJ/m2),적설(cm),dateName,locdate,holiday
0,2019-01-01 01:00:00,0.0,정문,2019,1,1,1,1,-5.9,0.0,1.8,56.0,0.0,0.0,0.0,1월1일,2019-01-01 00:00:00,1.0
1,2019-01-01 01:00:00,0.0,후문,2019,1,1,1,1,-5.9,0.0,1.8,56.0,0.0,0.0,0.0,1월1일,2019-01-01 00:00:00,1.0
2,2019-01-01 01:00:00,0.0,구의문,2019,1,1,1,1,-5.9,0.0,1.8,56.0,0.0,0.0,0.0,1월1일,2019-01-01 00:00:00,1.0
3,2019-01-01 02:00:00,0.0,정문,2019,1,1,2,1,-6.5,0.0,1.2,60.0,0.0,0.0,0.0,1월1일,2019-01-01 00:00:00,1.0
4,2019-01-01 02:00:00,0.0,후문,2019,1,1,2,1,-6.5,0.0,1.2,60.0,0.0,0.0,0.0,1월1일,2019-01-01 00:00:00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22675,2019-11-11 23:00:00,0.0,후문,2019,11,11,23,0,8.9,0.0,2.0,66.0,0.0,0.0,0.0,0,0,0.0
22676,2019-11-11 23:00:00,0.0,구의문,2019,11,11,23,0,8.9,0.0,2.0,66.0,0.0,0.0,0.0,0,0,0.0
22677,2019-11-12 00:00:00,0.0,정문,2019,11,12,0,1,7.9,0.0,1.0,71.0,0.0,0.0,0.0,0,0,0.0
22678,2019-11-12 00:00:00,0.0,후문,2019,11,12,0,1,7.9,0.0,1.0,71.0,0.0,0.0,0.0,0,0,0.0
22679,2019-11-12 00:00:00,0.0,구의문,2019,11,12,0,1,7.9,0.0,1.0,71.0,0.0,0.0,0.0,0,0,0.0

In [46]:
wch_17.to_csv('./data/[회귀]최종_전처리_완료_요일_날씨_공휴일_2017.csv', index=False)
wch_17.to_csv('./data/[회귀]최종_전처리_완료_요일_날씨_공휴일_2018.csv', index=False)
wch_19.to_csv('./data/[회귀]최종_전처리_완료_요일_날씨_공휴일_2019.csv', index=False)